### PR TITLE
Add deploy to Travis

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

https://github.com/crypto101/book/pull/356

### CODE REVIEW

**Comment by gliptak** [comment]
@lvh consider disabling https://travis-ci.org/crypto101/book/

**Comment by lvh** [comment]
@gliptak done (disabled .org)

**Comment by lvh** [comment]
I'm not sure how to use this since it requires a secret but I just did `travis setup releases --com` myself and pushed that to master here: https://github.com/crypto101/book/commit/0178348745788fc17ff8c49d13304e1429df7f05 -- we'll see if that works.

**Comment by lvh** [comment]
Hooray, it works! :) I guess I'll close this out.

**Comment by gliptak** [comment]
yes, you got an untagged release at https://github.com/crypto101/book/releases/download/untagged-7e0c1c2cd00146becd2b/Crypto101.pdf

**Pull request closed without merging**
