### PR TITLE
Write about SHA-1 hash function - v.2

### PR DESCRIPTION
**Pull request by EdOverflow**
I made a mess of the previous pull request, so I created a new one.

### CODE REVIEW

**Comment by qligier** [comment]
It could be interesting to add a few words about the recent SHA-1 deprecation in TLS certificates to emphasize that it's not considered secure enough.

**Comment by EdOverflow** [comment]
@qligier Good idea! I'll get right on it.

**Comment by lvh** [comment]
Thanks :) This ostensibly includes the change @qligier mentioned?

**Comment by EdOverflow** [comment]
Yep, now it does. :)

**Comment by lvh** [comment]
Thanks :)

**Pull request merged**
