### PR TITLE
Correct OCB Encryption diagram

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

https://github.com/crypto101/book/issues/419

### CODE REVIEW

**Comment by lvh** [comment]
I don't understand how this change works; the original name looks correct? At least there's `src/Illustrations/OCB/Encryption.mp`...

**Comment by gliptak** [comment]
@lvh yes this intends to avoid the duplicate generation issue by renaming. There might be something with

https://github.com/crypto101/book/blob/master/src/Makefile.assets#L85

I'm checking if generated PDF gets corrected

**Comment by gliptak** [comment]
so this restored Figure 6.4 on Page 32. if you are good with this workaround, I will add the other rename

the underlying cause might be caching during generation

**Comment by lvh** [comment]
Unfortunately Docker for Mac on M1 breaks comically; that's before the Ubuntu upgrade so I'll try again.

I'd very much like to figure out in more detail why this doesn't work before I'm comfortable merging it. Right now as it stands I don't understand why this change would fix anything at all and that's not a great feeling even if it does incidentally allegedly fix the build in 1 instance on 1 machine 😅

**Comment by gliptak** [comment]
reproduced this locally in Docker. MP -> SVG conversion produced the correct images.

The PDF file is incorrect, while the HTML pages have the correct images.

The error might be caused by https://github.com/missinglinkelectronics/sphinxcontrib-svg2pdfconverter

**Comment by gliptak** [comment]
looking into this further
```
find -name Encryption*.pdf
./_build_en/latex/Encryption2.pdf
./_build_en/latex/Encryption.pdf
./_build_en/doctrees/images/Encryption2.pdf
./_build_en/doctrees/images/Encryption.pdf
./_build_fr/latex/Encryption2.pdf
./_build_fr/latex/Encryption.pdf
./_build_fr/doctrees/images/Encryption2.pdf
./_build_fr/doctrees/images/Encryption.pdf
```
the generated PDF files are saved into flat space, so correction likely require rename as proposed

**Comment by lvh** [comment]
Not going to be able to get to this today, sorry. Somewhat annoyed that the Sphinx change means sure we got epub but we also got an unmaintainable system that breaks a bunch. And reStructured Text...

**Comment by gliptak** [comment]
@lvh would you like to see updates to this?

**Pull request closed without merging**
