### PR TITLE
Write about SHA-1 hash function.

### PR DESCRIPTION
**Pull request by EdOverflow**
Here is my first draft of the SHA-1 hash function chapter.

### CODE REVIEW

**Comment by lvh** [comment]
This seems to build on the MD5 branch and it looks like that one's almost done, so I'll hold off reviewing this until that merges.

**Comment by lvh** [comment]
This has some conflicts in the BiBTeX file. Could you merge forward or rebase?

**Comment by EdOverflow** [comment]
Whoops, sorry about that. I have now resolved all conflicts.

**Comment by lvh** [comment]
Huh, that's weird. Why does this add new MD5 citations to BiBTeX (at least according to the GitHub diff)?

**Comment by EdOverflow** [comment]
Uhm... I don't know how I managed to do that.

**Comment by EdOverflow** [comment]
Do you have any recommendations on how to fix this? :)

**Comment by lvh** [comment]
The diff looks friendlier when I pull it down and diff it locally, but it still has some stuff that's been changed in master that it'd be changing back. Normally I'd expect a merge-forward to fix this, unless the merge commit prefers your own branch (where unrelated changes to the document are the "old" ones). Another alternative is rebasing. Could you either merge forward again, and, failing that, cherry-pick any changes you intended to make into a new branch?

Sorry this is such a mess; I dunno how it got in that state either.

**Comment by EdOverflow** [comment]
I am terribly sorry about for the mess I made. I have created a new branch & pull request here: #308

**Pull request closed without merging**
