### PR TITLE
Bump Ubuntu to 22.04 for Docker

### PR DESCRIPTION
**Pull request by gliptak**
#426

### CODE REVIEW

**Comment by gliptak** [comment]
```
Running Sphinx v4.3.2
making output directory... done

Extension error:
You must configure the bibtex_bibfiles setting
make: *** [Makefile:41: html] Error 2
```

**Comment by lvh** [comment]
FYI I found an online reference suggesting this is due to sphinx-bibtex: https://groups.google.com/g/linux.debian.bugs.dist/c/UA8AcY9VC9Q/m/YisUNhwXAAAJ

**Comment by gliptak** [comment]
Thank you. I'm reading through those. A possible way to correct is to `pip install` pinning instead of using system included. Or update `conf.py` to new specs. Thoughts?

**Comment by lvh** [comment]
Wait, why does pip install fix it? Is it because newer versions no longer have this requirement and Ubuntu 22.04 doesn't ship such a sufficiently newer version? Or is it because Ubuntu patched this in in the first place?

**Comment by lvh** [comment]
(Since we actually use bibtex, modifying conf.py seems like the obvious call.)

**Comment by gliptak** [comment]
between 1.x and 2.x there was API for sphinx-bibtex

after update, build is green

**Comment by lvh** [comment]
Hooray!

**Pull request merged**
