### PR TITLE
Add release job to GHA CI

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

```
git tag v0.6.1
git push origin tag v0.6.1
```

### CODE REVIEW

**Comment by gliptak** [comment]
i just noticed that the artifacts uploaded actually zip files. A single archive with pdf/epub/html included might work better. Thoughts?

https://github.com/crypto101/book/actions/runs/962709520

**Comment by lvh** [comment]
Definitely! We'd love to link to the releases directly.

**Comment by gliptak** [comment]
@lvh 

this is how a release looks

https://github.com/gliptak/gha_buildcontainer/releases/tag/v0.2.1

multiarchive

https://github.com/crypto101/book/actions/runs/962709520

single archive

https://github.com/crypto101/book/actions/runs/962817249

please let me know which one you prefer

PS I'm running into https://github.com/actions/upload-artifact/issues/74

**Comment by lvh** [comment]
I think https://github.com/crypto101/book/actions/runs/962709520 is the best because it lets you download the individual files (PDF/EPUB...) directly.

**Comment by gliptak** [comment]
thanks @lvh the one thing to mention is that the individual files are still zipped up (which seem to be GH file upload functionality?)

I will repush that previous commit

**Comment by gliptak** [comment]
@lvh any updates you would like to see?

**Review by lvh — APPROVED** [review]
Nope, looks great -- just haven't had time to review yet :)

**Pull request merged**
